# Generated by Django 5.1.7 on 2025-04-19 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=100)),
                ('question_text', models.CharField(max_length=2000)),
                ('answer_text', models.CharField(max_length=2000)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
